### ISSUE TITLE
Ipython notebooks for bernoulli mixture models.

### ISSUE THREAD

**Issue by BayesianHuman** [AmazaspShumik/Bayesian-Regression-Methods#13]
You have some cool ipython notebooks for implemented models but I did not found anything for bernoulli mixture model. Is it just me or there is no notebooks on bmm?

**Comment by AmazaspShumik** [comment]
You are right there are no notebooks for mixture models. I am currently busy implementing Bayesian Hidden Markov Model, after that I will add notebooks on mixture models.

**Comment by AmazaspShumik** [comment]
Hi, BayesianHuman

Here is first version of ipython notebook for bernoulli mixture model:
https://github.com/AmazaspShumik/sklearn-bayes/blob/master/ipython_notebooks_tutorials/mixture_models/example_bernoulli_mixture.ipynb.

I will try to add & improve ipython notebooks in future.

**Comment by BayesianHuman** [comment]
@AmazaspShumik 

Thanks, cool example. I found similar example on one of your other repositories. 

P.S.
Please use @ to notify another user about your message.

**Comment by AmazaspShumik** [comment]
Ok , sorry will do that
