### ISSUE TITLE
Grouped ARD Linear/Logit regression

### ISSUE THREAD

**Issue by ferrine** [AmazaspShumik/Bayesian-Regression-Methods#15]
Hi, have you thought about implementing ARD for grouped problem?

**Comment by AmazaspShumik** [comment]
I implemented group lasso for one of the multi-task learning problems at work about a year ago, but except than that I never dealt with grouped problems. I am planning some updates to RVM / ARD to improve speed and add new ipython tutorials, so I think I would not be able to work on ARD for grouped problems. However if you have ideas or python implementation you are more than welcome to contribute.
