### ISSUE TITLE
'BayesianLogisticRegression' object has no attribute '_mask_val'

### ISSUE THREAD

**Issue by ghost** [AmazaspShumik/Bayesian-Regression-Methods#23]
Hi,
Is this a known issue? 
Cant even run fit .... 
`blr=BayesianLogisticRegression(n_iter=300, tol=1e-5, fit_intercept=False, verbose=True)`

  clf.fit(X_train, y_train)
  File "/Library/Python/2.7/site-packages/skbayes/linear_models/bayes_logistic.py", line 87, in fit
    y_bin[~mask] = self._mask_val
AttributeError: 'BayesianLogisticRegression' object has no attribute '_mask_val'

**Comment by AmazaspShumik** [comment]
BayesianLogisticRegression is superclass, fit method is available in EBLogisticRegression and VBLogisticRegression, which are two different versions of BayesianLogisticRegression

**Comment by AmazaspShumik** [comment]
VBLogisticRegresion uses Variational Bayes + Jaakola&Jordan 
EBLogisticRegression uses Empirical Bayes + Laplace approximation.

Please use only algorithms listed here: https://github.com/AmazaspShumik/sklearn-bayes.

**Comment by AmazaspShumik** [comment]
I will add further comments to BayesianLogisticRegression class to avoid confusion

**Comment by ghost** [comment]
Hi,
Thanks :) 

I was following the example here: https://github.com/AmazaspShumik/sklearn-bayes/blob/master/ipython_notebooks_tutorials/type_II_logistic/bayesian_logistic_demo.ipynb which clearly instantiates:
`blr= BayesianLogisticRegression(tol_solver = 1e-5)`

So maybe that should be fixed, 
Regards,

**Comment by AmazaspShumik** [comment]
@QuantScientist 

I am updating code for the whole package, and these are old tutorials.
I removed links to these old ipython notebooks from README but forgot to delete them (my mistake). I am working on new ipython notebooks for linear models, should update them next week. 

Kind regards =)

**Comment by AmazaspShumik** [comment]
Hi,

I added several new ipython notebooks regarding classification: 

 1) Logistic Regression with ARD prior (SBL algorithm) [tutorial](https://github.com/AmazaspShumik/sklearn-bayes/blob/master/ipython_notebooks_tutorials/rvm_ard/ard_classification_demo.ipynb)

2) Variational Bayes Logistic Regression with ARD prior [tutorial](https://github.com/AmazaspShumik/sklearn-bayes/blob/master/ipython_notebooks_tutorials/rvm_ard/vbard_classification.ipynb)

3) Bayesian Logistic Regression (includes both Empirical Bayes and Variational Bayes) [tutorial](https://github.com/AmazaspShumik/sklearn-bayes/blob/master/ipython_notebooks_tutorials/linear_models/bayesian_logistic_regression_demo.ipynb)

**Comment by AmazaspShumik** [comment]
@QuantScientist 

I also deleted confusing tutorial, which used an old version of the package.
Hope this helps =)
