### ISSUE TITLE
ARD and RVR: variance of predicitve distribution, take inverse?

### ISSUE THREAD

**Issue by sophiegif** [AmazaspShumik/Bayesian-Regression-Methods#26]
Hello,
it seems that in the predict_dist functions, the variance output is calculated using this formula that seems true to me:
var=sigma^2+(K^T Sigma K)

In the code, sigma^2 (identified as alpha_) is directly the precision beta (in the fit method, self.alpha_   = beta). But the precision is usually the inverse of the variance (and seems to be calculated as the inverse of the variance, even in your initialization).

I think the code is good, just the predict_dist should be : 
var_hat = 1./self.alpha_ ( and not var_hat = self._alpha)
var_hat += ...
 
If my thoughts are false, please do correct me!
Thank you again, I know looking back to your code must be time consuming...

**Comment by AmazaspShumik** [comment]
I will need to double check, later today, but it seems you are right. (I assume you are speaking about code in fast_rvm.py, right ? ).
 Can you make pull request?

**Comment by sophiegif** [comment]
Yes, taking about fast_rvm.py
I just did pull request.

Thanks!

**Comment by AmazaspShumik** [comment]
Cool )

**Comment by AmazaspShumik** [comment]
Thanks for help, I accepted pull request
