### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by happycube** [AmazaspShumik/Bayesian-Regression-Methods#29]
I'd like to ask Kaggle to include this in their Python Docker image, but I can't figure out what the license is...

Thanks, Chad

**Comment by AmazaspShumik** [comment]
Hi Chad,

skbayes is distributed under 3-Clause BSD license ( My mistake it is not in README)

Thanks,
Amazasp

**Comment by davharris** [comment]
Hi @AmazaspShumik, can you clarify? This indicates an MIT license. https://github.com/AmazaspShumik/sklearn-bayes/blob/master/setup.py#L37

Is either license included in the repo itself, or is it just mentioned in this Issue?

Thanks for making such a great project!

**Comment by MattWenham** [comment]
The MIT License has recently been added 😊

**Comment by AmazaspShumik** [comment]
Yes, added MIT license as @MattWenham mentioned, closing this issue.
