### ISSUE TITLE
RuntimeWarning: divide by zero encountered in divide

### ISSUE THREAD

**Issue by mark0935git** [AmazaspShumik/Bayesian-Regression-Methods#36]
Hi

I met the following warning when I was tuning  parameters for RVR.

**fast_rvm.py:48: RuntimeWarning: divide by zero encountered in divide
  deltaL[recompute] = Qrec**2 / (Srec + 1. / delta_alpha) - np.log(1 + Srec*delta_alpha)**

What is the potential reason for this warning?

**Comment by xavisuau** [comment]
+1. Same problem here.

**Comment by MattWenham** [comment]
I am hitting a similar error when trying to run the [Relevance Vector Machine Jupyter Notebook](https://github.com/AmazaspShumik/sklearn-bayes/blob/master/ipython_notebooks_tutorials/rvm_ard/rvm_demo.ipynb) on Windows 10.

The log terms in lines 47-49 of `fast_rvm.py` are sometimes being given negative values as arguments.

**Comment by mshangiti** [comment]
+1 same issue. It seems to happen on some dataset, while behave normally on others, I could not pinpoint the issue yet. Anyone found a solution to this?

**Comment by Bpoole908** [comment]
Did anyone ever discover the issue or reasoning here?
