### ISSUE TITLE
Loading the package

### ISSUE THREAD

**Issue by alexvicegrab** [AmazaspShumik/Bayesian-Regression-Methods#8]
Hi,

I've not really been able to use the package yet. I have tried installing it using the pip installer, which did not work.

Instead, I have cloned the package and tried to do python setup.py install, which worked, but the code examples don't seem to work.

I realised that I have to probably import sklearn_bayes, but when I dir it, it contains nothing beyond:
['**all**',
 '**builtins**',
 '**doc**',
 '**file**',
 '**name**',
 '**package**',
 '**path**',
 '**version**']

Am I doing something wrong?

**Comment by AmazaspShumik** [comment]
Hi,

No you are not doing anything wrong, you will basically need to import modules of package.

I wrote small ipython notebook , I hope it will help to solve the problem :
https://github.com/AmazaspShumik/sklearn_bayes/blob/master/ipython_notebooks_tutorials/quick_start.ipynb

**Comment by alexvicegrab** [comment]
Great, thank you for the swift response!
